version: '3.8'

services:
  flask-app:
    image: 'chatbot_flask:latest'
    container_name: chatbot_flask_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    environment:
      FLASK_APP: src/app.py
      FLASK_ENV: development
    volumes:
      - ./src:/src
      - ./model_store:/model_store
      - ./outputs:/outputs
    